apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
      - name: ticket-app
        image: <dockerhub_username>/ticket-app:latest
        ports:
        - containerPort: 5000
